version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx_server
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./logs:/var/log/nginx
    depends_on:
      - app
    networks:
      - app_network

  app:
    image: ghcr.io/lokendarjangid/next-logo-gen:latest
    container_name: next-logo-gen
    restart: always
    environment:
      - NEBIUS_API_KEY=${NEBIUS_API_KEY}
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
