services:
  app:
    image: ghcr.io/lokendarjangid/next-logo-gen:latest
    container_name: next-logo-gen
    ports:
      - "80:3000"
    environment:
      - NEBIUS_API_KEY=${NEBIUS_API_KEY}
    restart: always