services:
  app:
    image: ${DOCKER_USERNAME}/next-logo-gen:latest
    container_name: next-logo-gen
    ports:
      - "3000:80"
    environment:
      - NEBIUS_API_KEY=${NEBIUS_API_KEY}
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3