version: '3.8'

services:
  app:
    image: ${DOCKER_USERNAME}/next-logo-gen:latest
    container_name: next-logo-gen
    ports:
      - "3000:3000"
    environment:
      - NEBIUS_API_KEY=${NEBIUS_API_KEY}
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3

  nginx:
    image: nginx:1.24
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    restart: unless-stopped
