apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: default
stringData:
  NEBIUS_API_KEY: "${NEBIUS_API_KEY}"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: default
data:
  nginx.conf: |
    worker_processes 4;
    events {
        worker_connections 1024;
    }
    http {
        include mime.types;
        default_type application/octet-stream;
        sendfile on;
        keepalive_timeout 65;
        upstream app_backend {
            server next-logo-gen-service.default.svc.cluster.local:3000;
        }
        server {
            listen 80;
            location / {
                proxy_pass http://app_backend;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
            }
        }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: next-logo-gen
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: next-logo-gen
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1 # Allows one extra pod to be created during the update
      maxUnavailable: 1 # Ensures at least one pod is always available
  template:
    metadata:
      labels:
        app: next-logo-gen
    spec:
      containers:
        - name: next-logo-gen
          image: ghcr.io/lokendarjangid/next-logo-gen:latest
          env:
            - name: NEBIUS_API_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: NEBIUS_API_KEY
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-server
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-server
  template:
    metadata:
      labels:
        app: nginx-server
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-config-volume
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
      volumes:
        - name: nginx-config-volume
          configMap:
            name: nginx-config
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: default
spec:
  selector:
    app: nginx-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: next-logo-gen-service
  namespace: default
spec:
  selector:
    app: next-logo-gen
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
