name: Deploy

on:
  push:
    branches: [main]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.G_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ github.repository_owner }}/next-logo-gen:${{ steps.package-version.outputs.current-version}}
            ${{ env.REGISTRY }}/${{ github.repository_owner }}/next-logo-gen:latest

      - name: Copy docker-compose.yml to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.IP_ADDRESS }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.SSH_KEY }}
          source: "docker-compose.yml"
          target: "~/next-logo-gen"

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.IP_ADDRESS }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/next-logo-gen
            echo "DOCKER_IMAGE=ghcr.io/${{ github.repository_owner }}/next-logo-gen:latest" > .env
            echo "NEBIUS_API_KEY=${{ secrets.NEBIUS_API_KEY }}" >> .env
            docker compose pull
            docker compose up -d --remove-orphans
            docker image prune -f
