name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and deploy
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/next-logo-gen:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/next-logo-gen:latest

      - uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.IP_ADDRESS }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/next-logo-gen
            echo "DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}" > .env
            echo "NEBIUS_API_KEY=${{ secrets.NEBIUS_API_KEY }}" >> .env
            docker compose pull
            docker compose up -d --remove-orphans
