name: Deploy Application

on:
  push:
    branches: [main]

env:
  DOCKER_IMAGE: ${{ secrets.DOCKER_USERNAME }}/next-logo-gen

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        env:
          IMAGE_TAG: ${{ github.sha }}
          NEBIUS_API_KEY: ${{ secrets.NEBIUS_API_KEY }}
        run: |
          docker build -t $DOCKER_IMAGE:$IMAGE_TAG .
          docker push $DOCKER_IMAGE:$IMAGE_TAG
          docker tag $DOCKER_IMAGE:$IMAGE_TAG $DOCKER_IMAGE:latest
          docker push $DOCKER_IMAGE:latest

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.IP_ADDRESS }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.SSH_KEY }}
          script: |
            echo "NEBIUS_API_KEY=${{ secrets.NEBIUS_API_KEY }}" > .env
            docker pull ${{ secrets.DOCKER_USERNAME }}/next-logo-gen:latest
            docker compose down || true
            docker compose up -d
            # Verify container is running
            if ! docker ps | grep next-logo-gen; then
              echo "Container failed to start. Checking logs..."
              docker compose logs
              exit 1
            fi
            docker image prune -f
