name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.G_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ghcr.io/${{ secrets.DOCKER_USERNAME }}/next-logo-gen:latest

      - name: Copy docker-compose.yml to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.IP_ADDRESS }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.SSH_KEY }}
          source: "docker-compose.yml"
          target: "~/next-logo-gen"

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.IP_ADDRESS }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/next-logo-gen
            echo "DOCKER_IMAGE=ghcr.io/${{ github.repository_owner }}/next-logo-gen:latest" > .env
            echo "NEBIUS_API_KEY=${{ secrets.NEBIUS_API_KEY }}" >> .env
            docker compose pull
            docker compose up -d --remove-orphans
